### ISSUE TITLE
Test Temperature Sensor Working

### ISSUE THREAD

**Issue by ishassharmaa** [cu-ecen-aeld/final-project-ishassharmaa#1]
Develop Code to test the Temperature Sensor.

DoD: The temperature sensor should transmit the correct temperature value using Raspbian OS. 

Blockers: Obtaining remote transmission error

**Comment by SrirajVemparala** [comment]
Successfully Implemented Temperature sensor interface with RPi and received temperature value on Raspbian OS. 
Link to the code commit: [Commit changes](https://github.com/cu-ecen-aeld/final-project-SrirajVemparala/commit/16f287cff9c646978cb3f082d6a19eb9e6f337ba) 
![WhatsApp Image 2024-03-30 at 00 35 06_cf4311ad](https://github.com/cu-ecen-aeld/final-project-ishassharmaa/assets/91862302/d2688a8a-54e0-4c8b-a74a-06fae08677e5)
