### ISSUE TITLE
Rpi Buildroot Implementation with Sensor

### ISSUE THREAD

**Issue by ishassharmaa** [cu-ecen-aeld/final-project-ishassharmaa#2]
Develop Buildroot for Raspberry Pi + Sensor Integration.

DoD: The Temperature sensor should work successfully after buildroot implementation. 

Blockers: none

**Comment by SrirajVemparala** [comment]
1. Implemented Buildroot.
2. Added WiFi configurations.
3. Successfully Implemented Linux buildroot  Temperature sensor interface with RPi and received temperature values.
Link to the code commit:[Commit changes](https://github.com/cu-ecen-aeld/final-project-SrirajVemparala/commit/559a957852c206c395cc83489daded967fa27667)
Link to working application code- [mlxcode](https://github.com/SrirajVemparala/AESD_application_code/tree/main/MLX_code)
Link to working build root with wifi code- [buildroot](https://github.com/cu-ecen-aeld/final-project-SrirajVemparala/commit/559a957852c206c395cc83489daded967fa27667)

![Image](https://github.com/cu-ecen-aeld/final-project-ishassharmaa/assets/91862302/d59f1955-d8b2-4474-b6a9-4e7ac1d7a39f)
