### ISSUE TITLE
Socket Server

### ISSUE THREAD

**Issue by ishassharmaa** [cu-ecen-aeld/final-project-ishassharmaa#4]
Socket Server Implementation built on top of the Temp+Rpi.

DoD: The socket should work as a Server and connect successfully with the client, transferring the temperature sensor data. 

Blockers: Automatically not connecting to the wifi. --->solved by adding it in init script
               Implementing socket in blocking mode to wait to connect to the server.

**Comment by SrirajVemparala** [comment]
Transmitting server information successfully
[Final commit code link](https://github.com/cu-ecen-aeld/final-project-ishassharmaa/commit/e62ea8a39a82f642a55822b9ae959de19bcb9d76)
[Final commit Buildroot link](https://github.com/cu-ecen-aeld/final-project-SrirajVemparala/commit/a0431bbc5f4ef36205f12e9126abaf8eb7db5e98)


![Image](https://github.com/cu-ecen-aeld/final-project-ishassharmaa/assets/91862302/84fbf3a8-1f0a-4d90-952a-e39d00ae4d39)
